### ISSUE TITLE
Unable to take screenshot

### ISSUE THREAD

**Issue by marcusrc** [DevExpress/testcafe-browser-provider-electron#29]
**ENV:**
```
system:  mac 10.13.2
node:    v10.1.0
npm:     6.3.0
```

**Steps to reproduce:**

1. Clone **testcafe-browser-provider-electron** repo
2. Run npm install
3. Run npm test

**Expect:**

Tests pass

**Actual:**
```
 Screenshot
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/Users/**/testcafe-browser-provider-electron/.screenshots/screenshot-SKQn59.png'
Emitted 'error' event at:
    at fs.js:2076:12
    at FSReqWrap.oncomplete (fs.js:152:20)
```

**Comment by bbonczek** [comment]
This one is fixed now after testcafe v.1.7. Great!

**Comment by AlexSkorkin** [comment]
This is great news. Thank you for confirmation.
