### ISSUE TITLE
Errors related to starting electron are challenging to debug

### ISSUE THREAD

**Issue by Raynos** [DevExpress/testcafe-browser-provider-electron#55]
When a `testcafe` test fails to start electron the output is cryptic.

This highly likely related to hiding the output of `stdout` & `stderr` when spawning electron as a child process.

This would be addressed by https://github.com/DevExpress/testcafe-browser-provider-electron/pull/53

```
ERROR Was unable to open the browser "electron:" due to error.

Error: Unable to connect
    at NodeDebug._callee2$ (/home/runner/.config/npm-bin-deps/logs/node_modules/testcafe-browser-provider-electron/lib/node-debug.js:158:39)
    at tryCatch (/home/runner/.config/npm-bin-deps/logs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/runner/.config/npm-bin-deps/logs/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/runner/.config/npm-bin-deps/logs/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/runner/.config/npm-bin-deps/logs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/runner/.config/npm-bin-deps/logs/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by AlexKamaev** [comment]
Thank you for your suggestion. We need to discuss the supposed change with the team.

**Comment by AlexKamaev** [comment]
fixed in https://github.com/DevExpress/testcafe-browser-provider-electron/pull/53

**Comment by Raynos** [comment]
Thanks for fixing this !
