### ISSUE TITLE
Issues related to connecting to Electron with node-debug are challenging to debug.

### ISSUE THREAD

**Issue by Raynos** [DevExpress/testcafe-browser-provider-electron#59]
When I run testcafe on CI sometimes I get this output

```
2020-02-10T11:43:34.247Z testcafe:browser-provider-electron:spawn:stderr Debugger listening on ws://127.0.0.1:34035/9326ff05-f1e6-46d0-acf9-2b5fad36d7e3
For help, see: https://nodejs.org/en/docs/inspector
ERROR Was unable to open the browser "electron:" due to error.

Error: Unable to connect
    at NodeDebug._callee2$ (/home/runner/.config/npm-bin-deps/logs/node_modules/testcafe-browser-provider-electron/lib/node-debug.js:158:39)
    at tryCatch (/home/runner/.config/npm-bin-deps/logs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/runner/.config/npm-bin-deps/logs/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/runner/.config/npm-bin-deps/logs/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/runner/.config/npm-bin-deps/logs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/runner/.config/npm-bin-deps/logs/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

I've already opted into printing STDOUT / STDERR as can be seen from

```
2020-02-10T11:43:34.247Z testcafe:browser-provider-electron:spawn:stderr Debugger listening on ws://127.0.0.1:34035/9326ff05-f1e6-46d0-acf9-2b5fad36d7e3
```

However the debugger was not able to attach and all I get is UNable to connect.

One of the issues is here 

```
  return await connectionPromise
            .then(() => true)
            .catch(() => {
                this.socket.removeAllListeners('connect');
                return delay(connectionRetryDelay);
            });
```

The testcafe library catches errors and does not print why it was not able to open a TCP socket.

Also another issue might just timing and delays, The connection retry delay is a static number of 300ms * 10 attempts.

Using exponential backoff could help. this could be an array of [100, 300, 300, 600, 1000, 1000, 1000, 1000, 1000, 2500] where you index the retry delay time by the current attempt counter.

**Comment by alexey-lin** [comment]
Hi @Raynos,

Thank you for your suggestion. It's a good idea. Your PR would be highly appreciated.

**Comment by AndreyBelym** [comment]
The node-debug module was removed in v0.0.19
